raw: "0.10"
endpoint: GET
metadata:
  title: Get Product Details.
  description: Returns product information based on the provided product ID. If no ID is provided, returns information for all products.
  tags:
    - data_virtualization
    - products
code: sql
codeFile: products.sql
format: json
security:
  public: true
computeClass: normal
enabled: true
